from langchain_core.prompts import ChatPromptTemplate

properties_prediction_prompt = """You are an expert in the synthesis of nanomaterials. 
You analyze the conditions for obtaining a nanomaterial and predict what particle shapes will be present in the synthesized material. 
There are five particle shapes: 'Cube', 'Stick', 'Sphere', 'Flat' and 'Amorphous'. 
A nanomaterial can contain particles of different shapes. If you cannot say exactly what it is list the shapes that have the highest probability in those conditions. 
You will be given several examples of the synthesis and the respective nanomaterial shapes, after that you have to list the shapes for the new synthesis. 
As an answer PLEASE ONLY LIST SHAPES OF NANOMATERIALS FOR THE LAST SYNTHESIS.\n
Example 1: All materials were synthesized via the co-precipitation technique. In the first step, 102 mkl of 1 M CaCl2 was combined with 20 mkl of 0.35 % wt. PSS polymer, characterized by a molecular weight of 1000.0 kDa. This was followed by the addition of 0.0 mkl of No_solvent, and the volume was adjusted to 500 mkl using distilled water. In the subsequent step, 275 mkl of 0.1 M Na2CO3, 0 mkl of 0.1 M NaHCO3, and 20 mkl of 0.014625 % wt. Hexadecyltrimethylammonium bromide surfactant were combined. Again, 0.0 mkl of No_solvent was added, and the volume was adjusted to 500 mkl using distilled water. Finally, two solutions, both heated to 46 C before the reaction, were mixed under stirring at 730 rpm while maintaining the temperature. The reaction proceeded for 405 min, followed by centrifugation. 
Shapes: Amorphous, Cube\n
Example 2: Regardless of the prepared sample, the procedure of co-precipitation was the same and as it is described hereafter. Firstly, 50 mkl of 1 M CaCl2 was mixed with 20 mkl of 0.0 % wt. No_polymer with 0.0 kDa molecular weight. 7.8 mkl of tert-Butanol solvent was also added to the solution. Subsequently, an aqueous solution with volume of 500 mkl containing 74 mkl of 0.1 M Na2CO3 and 186 mkl of 0.1 M of NaHCO3 was prepared with 20 mkl of 1.175 % wt. Myristyltrimethylammonium bromide as surfactant and 7.8 mkl of tert-Butanol solvent. These solutions were heated up to 50 C, were mixed under the stirring with 0 rpm, while the temperature kept unchanged. Reaction proceeded for 255 min following centrifugation. 
Shapes: Stick, Cube\n
Example 3: All materials were synthesized via the co-precipitation technique. In the first step, 51 mkl of 1 M CaCl2 was combined with 20 mkl of 0.0 % wt. No_polymer polymer, characterized by a molecular weight of 0.0 kDa. This was followed by the addition of 17.4 mkl of Ethylene glycol, and the volume was adjusted to 500 mkl using distilled water. In the subsequent step, 0 mkl of 0.1 M Na2CO3, 140 mkl of 0.1 M NaHCO3, and 20 mkl of 0.09 % wt. Myristyltrimethylammonium bromide surfactant were combined. Once more, 17.4 mkl of Ethylene glycol was added, and the volume was adjusted to 500 mkl using distilled water. Finally, two solutions, both heated to 22 C before the reaction, were mixed under stirring at 690 rpm while maintaining the temperature. The reaction proceeded for 930 min, followed by centrifugation. 
Shapes: Sphere, Cube\n
Example 4: CaCO3 nanoparticles were synthesized by the co-precipitation approach according to the following manner. In separate burettes two solutions were made, 70 mkl of 1 M CaCl2 and 20 mkl of 0.8 % wt. PSS with molecular weight of 1000.0 kDa were mixed in 0.0 mkl of No_solvent before dilution with distilled water up to 500 mkl. Similarly, 44 mkl of 0.1 M Na2CO3 and 76 mkl of 0.1 M of NaHCO3 were combined with 20 mkl of 0.025 % wt. Sodium dodecylsulfate and 0.0 mkl of No_solvent. Then, the solution was also diluted in 500 mkl of water. Both solutions were heated up to 65 C right before mixing under stirring at 0 rpm for 2079 min following centrifugation. 
Shapes: Amorphous\n
Example 5: Nanoparticles under research have been obtained using the co-precipitation method. First, 0 mkl of 0.1 M Na2CO3 has been mixed with 163 mkl of 0.1 M of NaHCO3 and 20 mkl of 0.005625 % wt. Hexadecyltrimethylammonium bromide. Then, No_solvent 0.0 mkl was added, following diluted up to 500 mkl with distilled water. Second, 69 mkl of 1 M CaCl2 has been mixed with 20 mkl of 0.1 % wt. PSS with molecular weight of 1000.0 kDa. Then, No_solvent 0.0 mkl was added, following adjustment up to 500 mkl by distilled water. Two obtained solutions, heated to 46 C, have been mixed under the stirring with 730 rpm, while the temperature was constant. Reaction proceeded for 475 min during centrifugation. 
Shapes: Flat\n
Example 6: All the materials have been synthesized by the co-precipitation technique of two mixtures. The first mixture was obtain by mixting of 0 mkl of 0.1 M Na2CO3 with 200 mkl of 0.1 M of NaHCO3 and 20 mkl of 0.045 % wt. Sodium dodecylsulfate as surfactant. 0.0 mkl of No_solvent was added as a solvent, and resulting mixture was adjustment with distilled water up to 500 mkl. The second mixture was obtained by mixting of 39 mkl of 1 M CaCl2 with 20 mkl of 0.3 % wt. PAA polymer with molecular weight of 2.1 kDa. 0.0 mkl of No_solvent was added as solvent, following adjustment with distilled water up to 500 mkl. Obtained mixtures were heated up to 50 C and mixed under the stirring with 0 rpm, while the temperature kept unchanged. Reaction proceeded for 290 min following centrifugation. 
Shapes: Sphere\n
New synthesis: {synthesis} 
Shapes: """


synthesis_generator_alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
{}
### Input:
{}
### Response:
{}"""

synthesis_generator_system_prompt = "You are a scientist, working with nanomaterial synthesis. You have to create a nanomaterial with specific shape. You also have to use specific reagents such as polymer, solvent and surfactant. Please provide a synthesis methodic to create a nanomatrial with the specified shape and reagents."


shape_detection_prompt = """What is the closest nanomaterial shape is the particle on the picture? Possible shapes are: Cube, Sphere, Stick, Flat, Amorphous. PLEASE ONLY ANSWER WITH ONE WORD THAT IS THE SHAPE OF NANOMATERIAL!"""


synthesis_few_shot = """

You are a scientist, working with nanomaterial synthesis. You have to create a nanomaterial with specific shape. You also have to use specific reagents such as polymer, solvent and surfactant. Please provide a synthesis methodic to create a nanomatrial with the specified shape and reagents. Here are several examples of user question and generated synthesis text.
Example 1: 
User: Please generate a synthesis with Stick and Cube nanoparticles.
AI: CaCO3 nanoparticles. 20 mkl of 0.05 % wt. Myristyltrimethylammonium bromide, 32 mkl of 0.1 M Na2CO3 and 4 mkl of 0.1 M of NaHCO3 were mixed in 0.0 mkl of No_solvent, then the mixture was diluted dy distilled water up to 500 mkl. Further, 20 mkl of 0.795 % wt. PVP with molecular weight of 40.0 kDa and 93 mkl of 1 M CaCl2 have been mixed in 0.0 mkl of No_solvent, the mixture was diluted to 500 mkl by distilled water. Resulting solutions have been heated to 46 C and mixed for stirring with 730 rpm during 495 min with unchanged temperature.
Example 2: 
User: Please generate a synthesis with Sphere nanoparticles with 1-Hexanol solvent.
AI: The co-precipitation technique was employed for the synthesis of all materials. To initiate the process, 93 mkl of 1 M CaCl2 was mixed with 20 mkl of 0.325 % wt. PSS polymer (having a molecular weight of 1000.0 kDa). Following this, 20.0 mkl of 1-Hexanol was added, and the volume adjusted to 500 mkl using distilled water. Subsequently, a mixture of 0 mkl of 0.1 M Na2CO3, 66 mkl of 0.1 M NaHCO3, and 20 mkl of 0.0 % wt. No_surfactant surfactant was prepared. Once more, 20.0 mkl of 1-Hexanol was added, and the volume adjusted to 500 mkl using distilled water. Finally, two solutions, both heated to 64 C before the reaction, were mixed under stirring at 0 rpm while maintaining the temperature. The reaction proceeded for 1150 min, followed by centrifugation.
Example 3: 
User: Please generate a synthesis with Amorphous nanoparticles without polymer.
AI: All the materials have been synthesized by the co-precipitation method. Firstly, 37 mkl of 1 M CaCl2 was mixed with 20 mkl of 0.0 % wt. No_polymer polymer with 0.0 kDa molecular weight. Then, 8.0 mkl of 1-Hexanol was added, following adjustment up to 500 mkl by distilled water. Secondly, 98 mkl of 0.1 M Na2CO3 was mixed with 40 mkl of 0.1 M of NaHCO3 and 20 mkl of 0.285 % wt. Myristyltrimethylammonium bromide. Then, 8.0 mkl of 1-Hexanol was added, following adjustment with distilled water up to 500 mkl. Two resulting solutions, heated up to 26 C before the reaction, were mixed under the stirring with 0 rpm, while the temperature kept unchanged. Reaction proceeded for 1144 min following centrifugation.
Example 4: 
User: Please generate a synthesis with Sphere and Cube nanoparticles.
AI: The co-precipitation technique was employed for the synthesis of all materials. To initiate the process, 146 mkl of 1 M CaCl2 was mixed with 20 mkl of 0.0 % wt. No_polymer polymer, characterized by a molecular weight of 0.0 kDa. Following this, 9.0 mkl of Dimethylformamide was added, and the volume adjusted to 500 mkl using distilled water. Next, 131 mkl of 0.1 M Na2CO3, 36 mkl of 0.1 M NaHCO3, and 20 mkl of 0.28 % wt. Myristyltrimethylammonium bromide surfactant were combined. Again, 9.0 mkl of Dimethylformamide was added, and the volume was adjusted to 500 mkl using distilled water. Finally, two solutions, both heated to 22 C before the reaction, were mixed under stirring at 690 rpm while maintaining the temperature. The reaction proceeded for 940 min, followed by centrifugation.
Example 5: 
User: Please generate a synthesis with Stick and Amorphous nanoparticles without toxicc polymers or solvents.
AI: The co-precipitation technique was used to synthesize CaCO3 nanoparticles. 38 mkl of 1 M CaCl2, 20 mkl of 0.0 % wt. No_polymer polymer with molecular weight of 0.0 kDa and 0.0 mkl of No_solvent were mixed in distilled water so that the final volume of the solution was 500 mkl. Another solution was made up the same way, containing a 92 mkl of 0.1 M Na2CO3, 0 mkl of 0.1 M of NaHCO3 and 20 mkl of 0.0 % wt. No_surfactant as a surfactant. The 0.0 mkl of No_solvent solvent was added and it was also diluted with distilled water up to 500 mkl. After heating up to 50 C the solutions were mixed under the stirring with 0 rpm for 1170 min at this temperature following centrifugation.
Example 6: 
User: Please generate a synthesis with Flat nanoparticles.
AI: The co-precipitation technique was employed for the synthesis of all materials. To initiate the process, 295 mkl of 1 M CaCl2 was mixed with 20 mkl of 0.28 % wt. PAA polymer, characterized by a molecular weight of 2.1 kDa. Following this, 0.0 mkl of No_solvent was added, and the volume adjusted to 500 mkl using distilled water. Next, 260 mkl of 0.1 M Na2CO3, 83 mkl of 0.1 M NaHCO3, and 20 mkl of 0.0 % wt. No_surfactant surfactant were combined. Again, 0.0 mkl of No_solvent was added, and the volume was adjusted to 500 mkl using distilled water. Finally, two solutions, both heated to 58 C before the reaction, were mixed under stirring at 0 rpm while maintaining the temperature. The reaction proceeded for 1699 min, followed by centrifugation.


Your objective is:

{query}
"""

synt_prompt = ChatPromptTemplate.from_template(synthesis_few_shot)


entr_eff = """
Your task is to predict the entrapment efficiency for specific nanoparticles based on their synthesis text and other parameters such as drug used or nanoparticle shape. Please answer only with the entrapment efficiency value which cannot exceed 100%. Here are several examples of syntheses provided by user and entrapment efficiencies that should be predicted:
Example 1:
Synthesis text: Synthesis of calcium carbonate nanocrystals were carried out in oil-in-water (O/W) microemulsions using a higher pressure homogeniser (HPH). In this technique, the particle sizes are reduced after leaving the homogenising gap by cavitations, particle collisions, and shear forces. Drug loaded calcium carbonate nanocrystals were prepared by adding an aqueous solution of doxorubicin hydrochloride (1 mg/mL) into the calcium carbonate nanocrystal suspension (containing 20 mg of nanocrystals). The encapsulation of Dox in CaCO3 nanocrystals was achieved by continuous stirring of the suspension mixture in the dark overnight at room temperature. Calcium carbonate nanocrystals containing Dox were washed, centrifuged and oven dried (FD 115, Fisher Scientific, Limburg, Germany) at 55 °C.
Entrapment efficiency: 97%
Example 2:
Synthesis text: All the experiments were prepared at room temperature. Etoposide-loaded calcium carbonate nanospheres were synthesized by mixing calcium chloride and sodium carbonate aqueous solution in the presence of ethanol, citric acid, and etoposide. Etoposide (0.2 g) and 10 mL CaCl2 (0.1 M) were dissolved in 60 mL mixed solvent of ethanol and deionized water (volume ratio = 1:2), marked as solution A. Na2CO3 (0.02 g) and 10 mL of Na2CO3 (0.1 M) were dissolved in 60 mL mixed solvent of ethanol and deionized water (volume ratio = 1:2), marked as solution B. Solution B was added dropwise to the vigorously stirred solution A. With the reaction proceeding, the milky white precipitation was obtained after 72 h at room temperature. The precipitation was washed thrice with mixed solvent of ethanol and deionized water (volume ratio = 1:2) and dried using vacuum freeze drier. The blank carrier CCNSs were prepared without the addition of etoposide, and other experimental parameters were similar to the ECCNSs sample.
Entrapment efficiency: 39.7%
Example 3:
Synthesis text: Calcium chloride (50 ml) (0.05 M), 10 ml of 1% SDS and 10 ml of 1% F68 were mixed by continuous stirring (300 r.p.m.) for 24 h to form microemulsion A; 50 ml of sodium carbonate (0.025 M), 50 ml of sodium citrate (0.025 M), 10 ml of 1% SDS and 10 ml 1% F68 were mixed by continuous stirring (300 r.p.m.) for 24 h to form microemulsion B. After 24 h, microemulsion B was slowly added to microemulsion A at the rate of 10 ml h1 with continuous stirring (350 r.p.m.) at 35 1C and then further stirred for 72 h after centrifugation at 15 000 r.p.m. for 15 min. The pelleted nanoparticles were washed four times with 75% ethanol, redispersed in 15 ml of double-distilled water by sonication (frequency 22 kHz; power 120W) for 1 h. The dispersed nanoparticles were quickly frozen at 70 1C for 2 h in an ultracold freezer, before being freeze dried over a 48 h period. The calcium carbonate nanoparticle powder was kept for use.
Entrapment efficiency: 65%
Example 4:
Synthesis text: Plasmid solution with 1 µg of plasmid DNA was diluted to 10 µl, and then 16 µl of CaCl2 solution (0.5 M) was added dropwise. The solution was diluted with deionized water to make solution A with a total volume of 60 µl. Protamine sulphate (0.15 µg) and KALA with a particular amount (0.1, 0.2, 0.5, 1, 2 and 5 µg, respectively) and 16 µl of Na2CO3 solution (0.01 M) were mixed and then diluted with deionized water to Page 7 of 27 RSC Advances make solution B with a total volume of 40 µl. Then solution A was added into solution B dropwise and mixed gently to obtain 100 µl of KALA/PS/CaCO3/DNA nanoparticles containing solution with 1 µg of DNA. For comparison, CaCO3/DNA nanoparticles were prepared by adding 60 µl of solution containing DNA (1 µg) and CaCl2 (8 µmol) to 40 µl of solution containing Na2CO3 (0.16 µmol), and mixing gently. PS/CaCO3/DNA nanoparticles were prepared by adding 60 µl of solution containing DNA (1 µg) and CaCl2 (8 µmol) to 40 µl of solution containing PS (0.15 µg) and Na2CO3 (0.16 µmol), and mixing gently. KALA/CaCO3/DNA nanoparticles were prepared by adding 60 µl of solution containing DNA (1 µg) and CaCl2 (8 µmol) to 40 µl of solution containing KALA (0.5 µg) and Na2CO3 (0.16 µmol), and mixing gently.
Entrapment efficiency: 96-99%
Example 5:
Synthesis text: The anionic lipid-coated CC core was prepared with a water-in-oil emulsion method. Briefly, 18 μL of 3% sodium carbonate buffer (pH 8.3) was mixed with the same volume of peptide (2 mg/mL) and was dispersed in 1 mL of a cyclohexane to form a well dispersed water-in-oil emulsion. The calcium solution was prepared by adding 20 μL of a calcium chloride solution (250 mM) to 1 mL of a cyclohexane oil phase. A 25 μL volume of a 25 mg/mL 1,2-dioleoyl-sn-glycero-3- phosphoethanolamine-N-(glutaryl) (DOPE-glu) solution dissolved in chloroform was added to the calcium phase. After mixing the above two solutions by sonication (15 sec, 3 times), the mixture was centrifuged at 8,000 × g for 1 min to remove the cyclohexane and excess surfactant. The core pellets were dispersed in 500 μL of water for liposomal formation with DOTAP/cholesterol (10 mg/mL). The LCC nanoparticles were further modified with 50 uL of DSPE-PEG-2000 (10 mg/mL) or DSPE-PEG-AA (10 mg/mL). The particle size and zeta potential of the finished LCC NPs were detected in 1 mM KCl using a Malvern ZetaSizer Nano series (Westborough, MA). To measure the loading efficiency of the EV peptide, free EV peptide labeled with Alexa-488 was measured after elimination of unreacted free Alexa-488 and unconjugated EV peptide using a dialysis membrane (MW: 2000). Transmission electron microscopy (TEM) images of the LCC NPs were acquired with the use of a JEOL 100CX II TEM (JEOL, Japan). The TEM sample of LCC NPs was prepared on a 300 mesh carbon coated copper grid (Ted Pella, Inc., Redding, CA).
Entrapment efficiency: 65-70%
Example 6:
Synthesis text: Betamethasone phosphate (BP) was incorporated into calcium carbonate nanoparticles (nano-CaCO3) by the following method: 650 Al of 5 M CaCl2 and 375 Al of 5% BSP were gently mixed for 10 min, and then 2.5 ml of 1 M Na2CO3 was added and stirred gently or vigorously for 10 min. After the addition of 5 ml of distilled water and discarding the large particles of nano-CaCO3 which were precipitated without centrifugation, the suspension was centrifuged (2000 rpm, 5 min) and the supernatant and precipitate were separated. The amount of BP in the supernatant and precipitate was measured respectively with HPLC, after dissolving the CaCO3 with 0.5 M EDTA (pH 7.5). The fabricated nano-CaCO3 containing BP were used for in vitro and in vivo experiments. We tested with different ratio in mole of CaCl2/ Na2CO3 at 1/1.6, 1/1.3, 1, 1.3, 1.6 and observed that the incorporation rate was highest at the ratio of 1.3, and used the ratio in this study. To study the adsorption of BP, we mixed 650 Al of 5 M CaCl2 and 2.5 ml of 1 M Na2CO3 and stirred gently or vigorously, according to desired particle size, and nano-CaCO3 were formed. After the particles were washed with 5 ml of distilled water, 375 Al of 5% BSP was added and stirred to adsorb BP. The resulting suspension was centrifuged (2000 rpm, 5 min) and the amount of BP in the precipitate was determined by the method described above.
Entrapment efficiency: 90.6-91.1%
Example 7:
Synthesis text: Erythropoietin was incorporated into nano-CaCO3 by mixing 650 Al of 5 M CaCl2 and 125 Al of 1 mg/ml erythropoietin, and then by adding 2.5 ml of 1 M Na2CO3 stirring gently for 10 min at room temperature. After the addition of 5 ml of distilled water, the suspension was divided into two parts and centrifuged (2000 rpm, 5 min). One part was used for the measurement of erythropoietin, and the other part was washed by 0.9 ml of 1 M Na2CO3 twice to eliminate the adsorbed erythropoietin on the nanoCaCO3. The both samples were dissolved by adding 1N HCl, and the amount of incorporated erythropoietin in the nano-CaCO3 was measured with an ELISA kit (Toyobo, Osaka, Japan). In the adsorption experiment with erythropoietin, 650 Al of 5 M CaCl2 and 2.5 ml of 1 M Na2CO3 were mixed and stirred initially, and nano-CaCO3 were formed. Next, the particles were washed by 5 ml of distilled water and 125 Al of 1 mg/ml erythropoietin was added and stirred to adsorb the erythropoietin. The resulting suspension was divided into two parts and centrifuged (2000 rpm, 5 min). The obtained precipitate of one part was used for the measurement of erythropoietin and that of the other part was washed twice by 0.9 ml of 1 M Na2CO3. The amount of erythropoietin of each part was determined by the method described above.
Entrapment efficiency: >90%

Your objective is:

{query}
"""

entr_eff_prompt = ChatPromptTemplate.from_template(entr_eff)
